name: Build docker image

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  build-docker-image:
    name: Build docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        package:
          #- srtool
          - safe-transaction-service
          - optimism
    steps:
      - uses: actions/checkout@v4

      - uses: benjlevesque/short-sha@v1.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}

      ## If new version required, please enable this.
      # - name: srtool
      #   uses: docker/build-push-action@v3
      #   if: ${{ matrix.package == 'srtool' }}
      #   env:
      #     RUST_TOOLCHAIN: nightly-2023-05-22
      #   with:
      #     push: true
      #     context: docker-image/srtool
      #     tags: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/srtool:${{ env.RUST_TOOLCHAIN }}
      #     build-args: |
      #       RUSTC_VERSION=${{ env.RUST_TOOLCHAIN }}

      - name: safe-transaction-service
        uses: docker/build-push-action@v3
        with:
          push: true
          context: docker-image/${{ matrix.package }}
          tags: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/${{ matrix.package }}:sha-${{ env.SHA }}

