name: Playground

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  test-artifact:
    name: Task artifact action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: [actions, docker-image]
    steps:
      - name: Upload shared
        uses: actions/upload-artifact@v4
        with:
          name: devops-artifact
          path: ${{ matrix.path }}
